language: node_js

node_js:
- 10
- stable

before_install:
- npm install -g npm@5

script:
- npm run lint
- npm run test -- --verbose

cache:
  directories:
  - node_modules

matrix:
  fast_finish: true
